services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./demo-app/
      dockerfile: ./Dockerfile.local
    container_name: spring-boot-app
    env_file: ./demo-app/.env.local
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - postgres

  newman:
    image: postman/newman:6-alpine
    volumes:
      - ./api-test/collection:/etc/newman
      - ./api-test/results:/etc/newman/results
    command: ["run", "postman_collection.json", "-e", "postman_environment.json", "-d", "datatest.csv", "--reporters", "cli,junit", "--reporter-junit-export", "results/report.xml"]
    depends_on:
      spring-boot-app:
        condition: service_healthy

volumes:
  postgres_data:
