FROM eclipse-temurin:22.0.1_8-jdk-ubi9-minimal as build
WORKDIR /app
COPY . /app
RUN ./mvnw install

FROM eclipse-temurin:22.0.1_8-jre-ubi9-minimal as runtime
WORKDIR /app
COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar /app
ENTRYPOINT ["java"]
CMD ["-jar", "demo-0.0.1-SNAPSHOT.jar"]